### ISSUE TITLE
`lightning-dns-resolver`'s `end_to_end` test is flaky

### ISSUE THREAD

**Issue by tnull** [lightningdevkit/rust-lightning#3863]
I just saw this failure in CI:

```
2025-06-16T10:18:10.7176510Z resolver: Received an onion message with a reply_path: DNSSECQuery(DNSSECQuery(Name("matt.user._bitcoin-payment.mattcorallo.com.")))
2025-06-16T10:18:10.7176946Z 
2025-06-16T10:18:10.7177145Z thread 'test::end_to_end_test' panicked at lightning-dns-resolver/src/lib.rs:401:13:
2025-06-16T10:18:10.7177501Z Resolution took too long
2025-06-16T10:18:10.7177695Z stack backtrace:
2025-06-16T10:18:10.7177871Z    0: __rustc::rust_begin_unwind
2025-06-16T10:18:10.7178241Z              at /rustc/17067e9ac6d7ecb70e50f92c1944e545188d2359/library/std/src/panicking.rs:697:5
2025-06-16T10:18:10.7178627Z    1: core::panicking::panic_fmt
2025-06-16T10:18:10.7178989Z              at /rustc/17067e9ac6d7ecb70e50f92c1944e545188d2359/library/core/src/panicking.rs:75:14
2025-06-16T10:18:10.7179437Z    2: lightning_dns_resolver::test::pay_offer_flow::{{closure}}
2025-06-16T10:18:10.7179720Z              at ./src/lib.rs:401:4
2025-06-16T10:18:10.7179991Z    3: lightning_dns_resolver::test::end_to_end_test::{{closure}}
2025-06-16T10:18:10.7180271Z              at ./src/lib.rs:522:4
2025-06-16T10:18:10.7180658Z    4: tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}::{{closure}}::{{closure}}
2025-06-16T10:18:10.7181378Z              at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.45.1/src/runtime/scheduler/current_thread/mod.rs:733:54
2025-06-16T10:18:10.7181912Z    5: tokio::task::coop::with_budget
2025-06-16T10:18:10.7182470Z              at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.45.1/src/task/coop/mod.rs:167:5
2025-06-16T10:18:10.7182921Z    6: tokio::task::coop::budget
2025-06-16T10:18:10.7183354Z              at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.45.1/src/task/coop/mod.rs:133:5
2025-06-16T10:18:10.7183943Z    7: tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}::{{closure}}
2025-06-16T10:18:10.7184704Z              at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.45.1/src/runtime/scheduler/current_thread/mod.rs:733:25
2025-06-16T10:18:10.7185598Z    8: tokio::runtime::scheduler::current_thread::Context::enter
2025-06-16T10:18:10.7186548Z              at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.45.1/src/runtime/scheduler/current_thread/mod.rs:432:19
2025-06-16T10:18:10.7187189Z    9: tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}
2025-06-16T10:18:10.7187827Z              at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.45.1/src/runtime/scheduler/current_thread/mod.rs:732:36
2025-06-16T10:18:10.7188452Z   10: tokio::runtime::scheduler::current_thread::CoreGuard::enter::{{closure}}
2025-06-16T10:18:10.7189093Z              at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.45.1/src/runtime/scheduler/current_thread/mod.rs:820:68
2025-06-16T10:18:10.7189661Z   11: tokio::runtime::context::scoped::Scoped<T>::set
2025-06-16T10:18:10.7190175Z              at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.45.1/src/runtime/context/scoped.rs:40:9
2025-06-16T10:18:10.7190696Z   12: tokio::runtime::context::set_scheduler::{{closure}}
2025-06-16T10:18:10.7191346Z              at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.45.1/src/runtime/context.rs:176:26
2025-06-16T10:18:10.7191847Z   13: std::thread::local::LocalKey<T>::try_with
2025-06-16T10:18:10.7192259Z              at /rustc/17067e9ac6d7ecb70e50f92c1944e545188d2359/library/std/src/thread/local.rs:311:12
2025-06-16T10:18:10.7192668Z   14: std::thread::local::LocalKey<T>::with
2025-06-16T10:18:10.7193058Z              at /rustc/17067e9ac6d7ecb70e50f92c1944e545188d2359/library/std/src/thread/local.rs:275:15
2025-06-16T10:18:10.7193462Z   15: tokio::runtime::context::set_scheduler
2025-06-16T10:18:10.7193928Z              at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.45.1/src/runtime/context.rs:176:9
2025-06-16T10:18:10.7194443Z   16: tokio::runtime::scheduler::current_thread::CoreGuard::enter
2025-06-16T10:18:10.7195154Z              at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.45.1/src/runtime/scheduler/current_thread/mod.rs:820:27
2025-06-16T10:18:10.7195762Z   17: tokio::runtime::scheduler::current_thread::CoreGuard::block_on
2025-06-16T10:18:10.7196354Z              at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.45.1/src/runtime/scheduler/current_thread/mod.rs:720:19
2025-06-16T10:18:10.7196998Z   18: tokio::runtime::scheduler::current_thread::CurrentThread::block_on::{{closure}}
2025-06-16T10:18:10.7197634Z              at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.45.1/src/runtime/scheduler/current_thread/mod.rs:200:28
2025-06-16T10:18:10.7198195Z   19: tokio::runtime::context::runtime::enter_runtime
2025-06-16T10:18:10.7198704Z              at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.45.1/src/runtime/context/runtime.rs:65:16
2025-06-16T10:18:10.7199268Z   20: tokio::runtime::scheduler::current_thread::CurrentThread::block_on
2025-06-16T10:18:10.7199873Z              at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.45.1/src/runtime/scheduler/current_thread/mod.rs:188:9
2025-06-16T10:18:10.7200428Z   21: tokio::runtime::runtime::Runtime::block_on_inner
2025-06-16T10:18:10.7200912Z              at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.45.1/src/runtime/runtime.rs:356:47
2025-06-16T10:18:10.7201538Z   22: tokio::runtime::runtime::Runtime::block_on
2025-06-16T10:18:10.7202010Z              at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.45.1/src/runtime/runtime.rs:330:13
2025-06-16T10:18:10.7202493Z   23: lightning_dns_resolver::test::end_to_end_test
2025-06-16T10:18:10.7202748Z              at ./src/lib.rs:507:3
2025-06-16T10:18:10.7203026Z   24: lightning_dns_resolver::test::end_to_end_test::{{closure}}
2025-06-16T10:18:10.7203312Z              at ./src/lib.rs:455:28
2025-06-16T10:18:10.7203546Z   25: core::ops::function::FnOnce::call_once
2025-06-16T10:18:10.7203954Z              at /rustc/17067e9ac6d7ecb70e50f92c1944e545188d2359/library/core/src/ops/function.rs:250:5
2025-06-16T10:18:10.7204361Z   26: core::ops::function::FnOnce::call_once
2025-06-16T10:18:10.7204851Z              at /rustc/17067e9ac6d7ecb70e50f92c1944e545188d2359/library/core/src/ops/function.rs:250:5
2025-06-16T10:18:10.7205363Z note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
2025-06-16T10:18:10.7205652Z 
2025-06-16T10:18:10.7205656Z 
2025-06-16T10:18:10.7205718Z failures:
2025-06-16T10:18:10.7205881Z     test::end_to_end_test
```

**Comment by TheBlueMatt** [comment]
I think this may just be the usual "CI doesn't have Internet access randomly" nonsense. IIRC that does does a real resolution and only swaps the result at the end.

**Comment by tnull** [comment]
> I think this may just be the usual "CI doesn't have Internet access randomly" nonsense. IIRC that does does a real resolution and only swaps the result at the end.

Right, the way to fix this would likely be to drop the dependency on live servers, possibly by means of mocking or otherwise.

**Comment by TheBlueMatt** [comment]
Yea, ideally tests shouldn't rely on internet, but this one is a bit tricky to get good coverage without :/

**Comment by TheBlueMatt** [comment]
Was finally able to debug this since we have self-hosted runners and I can watch the traffic and we hit it again. Looks like it was actually 8.8.8.8 rate-limiting TCP connections, which these tests rely on. In CI on the self-hosted runners I just intercept the connections and redirect them to a local instance of bind, which should fix it in CI. Its possible people see this locally but somehow I've never seen it so I'm thinking it was more to do with how many CI jobs we have. Gonna optimistically close this but if anyone sees it locally we can swap the test to 1.1.1.1 or try to figure out how to hard-code full proofs.

**Comment by tnull** [comment]
> Was finally able to debug this since we have self-hosted runners and I can watch the traffic and we hit it again. Looks like it was actually 8.8.8.8 rate-limiting TCP connections, which these tests rely on. In CI on the self-hosted runners I just intercept the connections and redirect them to a local instance of bind, which should fix it in CI. Its possible people see this locally but somehow I've never seen it so I'm thinking it was more to do with how many CI jobs we have. Gonna optimistically close this but if anyone sees it locally we can swap the test to 1.1.1.1 or try to figure out how to hard-code full proofs.

Hmm, interesting. Make me wonder if we should consider allowing giving multiple `SocketAddrs` to `OMNameResolver` and then doing round-robin load balancing, as otherwise user nodes resolving HRNs as a service might also run into being rate-limited rather quickly?

**Comment by tnull** [comment]
Reopening this as it's still failing CI on `main`. (cc @TheBlueMatt)

**Comment by TheBlueMatt** [comment]
Nope, that was a new machine that wasn't configured right :).
